name: palika
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^6.0.0
  get: ^4.6.5
  #fl_chart: ^0.50.6
  #charts_flutter: ^0.12.0
  #pie_chart: ^5.3.1
  google_nav_bar: ^5.0.6
  flutter_cupertino_datetime_picker: ^3.0.0
  intl: ^0.17.0
  nepali_utils: ^3.0.3
  nepali_date_picker: ^5.3.0
  google_maps_flutter: ^2.1.7
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  flutter_riverpod: ^1.0.4
  geolocator: ^8.2.1
  geocoding: ^2.0.4
  http: ^0.13.4
  dio: ^4.0.6
  find_dropdown: ^1.0.0
  dropdown_search: ^5.0.2
  #flutter_offline: ^2.1.0
  connectivity: ^3.0.6
  overlay_support: ^1.0.5
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
